name: Output details
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Details
        run: echo "${{ toJSON(github) }}"